### ISSUE TITLE
Two PCB's within the Zip file

### ISSUE THREAD

**Issue by vianjo** [AndreasW29/pypilot-tinypilot-mysolution-infos#1]
There appears to be two PCB's within the main Zip file, one with a single stepdown regulator and the second with two, one to the PI and the other to the arduino. Which is the latest version? I assume the one with two stepdown regulators.

**Comment by AndreasW29** [comment]
Hi,

thank you for feedback.
The files in the folder "gerber" are the right ones.
It´s the pcb with one step down regulator. 
You can compare the date of the files and then you will see that the files in the folder "gerber" are from November and the gerber files in the main folder are from October. So the actual ones are in the folder "gerber"

Sorry for the confusion.

Andreas

**Comment by AndreasW29** [comment]
Changed folder so that it´s clear.
